### ISSUE TITLE
linphone notification logos need changed

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/an-mobile-android#11]
In v0.0.2 the notification hasn't been changed to Accelerate Networks logo
![signal-2021-03-15-003727](https://user-images.githubusercontent.com/44306072/111119290-2ec7d900-8527-11eb-8176-c5bba5e79cca.jpg)

**Comment by danry25** [comment]
We also need to update the launch screen logo

**Comment by piajesse** [comment]
This is being tracked in #18
