### ISSUE TITLE
When you tap the quit button app, it should deregister the client

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/an-mobile-android#13]
![Screenshot_20210621-222140](https://user-images.githubusercontent.com/44306072/122868226-896b9080-d2df-11eb-996c-901d821093d4.png)

**Comment by thefinn93** [comment]
This will result in a button which silently disables incoming calls for the user, without warning them. Incoming calls are instantly reactivated when the app is launched again. Per my conversation with @piajesse, this is some kind of misguided attempt at a do not disturb. If we want a DND feature, we should build that. This ticket as described is a good way to get support calls and frustrated users.
