### ISSUE TITLE
Caller ID Not Easily Visible in Call

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/an-mobile-android#16]
**Describe the bug**
When on a call the only caller ID that gets shown is the CNAM and the tag (e.g. Support). The caller ID number is not visible unless the signal bars in the upper left corner are tapped.

When the signal bars are tapped it pulls up a menu that has the number but it shows the number @acceleratenetworks.sip.callpipe.com e.g. 2065551234@acceleratenetworks.sip.callpipe.com instead of just showing the number 2065551234.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
1. Receive a call
2. Answer call
3. Look for number of caller who you answered
4. See error, tap signal bars in upper left corner to see CID number

**Expected behavior**
Most phones show the caller ID of the number you're on a call with

**Please complete the following information**
 - Device: Samsung A71 5G
 - OS: Android 12
 - Version of the App 4.5.6.28+c9f668ab
 - Version of the SDK 5.0.71
 - 
**SDK logs**
Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go to About page, click on "Send logs" and copy/paste the link here.

**Adb logcat logs**
In case of a crash of the app, please also provide the stack trace of the crash using adb logcat.

**Screenshots**
[signal-2022-08-26-120758](https://user-images.githubusercontent.com/73979793/186974959-169e9b90-061f-473e-bd2f-039c384646ba.png)

**Additional context**

**Comment by danry25** [comment]
This issue appears to be resolved in the new Android v5.2 build

![image](https://user-images.githubusercontent.com/1683673/222990060-93e26493-b01a-4f8f-9f59-73b1e3e1be69.png)
