### ISSUE TITLE
On save of previous call information use sips: format

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/an-mobile-android#19]
**Describe the bug**
Inbound calls are coming in in sip:+14254997999@exampledomain.sip.callpipe.com format, but Linphone will only dial out with the sips format where the s is added to the SIP URI.

**Comment by piajesse** [comment]
This hasn't been changed, but on ALL outbound calls, `sip:` gets replaced with `sips:`, this WILL be an issue if any of our linphone users use TCP or UDP instead of TLS, but as configs are automated, and we default to TLS all the time, so this shouldn't be an issue
