### ISSUE TITLE
QR Code Provisioning

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/an-mobile-android#5]
Expand the FusionPBX app to generate a QR code that can be scanned by Linphone to provision the app to the correct SIP domain & extension.

Linphone appears to support QR Code provisioning, see the last section of the [Remote Provisioning page](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/).

**Comment by piajesse** [comment]
I need to work on this, it was disabled due to being broken in android, I should be able to test this in android studio

**Comment by danry25** [comment]
QR Code works in the v5.2 beta, but the URL needs to have an HTTPS in front.
